server {
    listen 80;
    location / {
        root /usr/share/nginx/html/0.9.3;
        add_header Cross-Origin-Resource-Policy cross-origin;
        add_header access-control-allow-origin *;
    }
}